//common

export const LOADING = "LOADING";
export const STOP_LOADING = "STOP_LOADING";

//HOTEL

export const FETCH_HOTELS_SUCCESS = "FETCH_HOTELS_SUCCESS";
export const FETCH_HOTELS_FAILED = "FETCH_HOTELS_FAILED";
export const ADD_HOTEL_SUCCESS = "ADD_HOTEL_SUCCESS";
export const ADD_HOTEL_FAILED = "ADD_HOTEL_FAILED";
export const REMOVE_HOTEL_SUCCESS = "REMOVE_HOTEL_SUCCESS";
export const REMOVE_HOTEL_FAILED = "REMOVE_HOTEL_FAILED";
export const EDIT_HOTEL_SUCCESS = "EDIT_HOTEL_SUCCESS";
export const EDIT_HOTEL_FAILED = "EDIT_HOTEL_FAILED";

